### ISSUE TITLE
gocsv isn't "go get"-able

### ISSUE THREAD

**Issue by kevinsumner** [aotimme/gocsv#13]
Would you be open to having gocsv be buildable and installable with `go get`?

**Comment by aotimme** [comment]
Apologies for the delayed response. I am open to having gocsv be buildable and installable with `go get`. I haven't looked into it at all to know what it requires, however. Do you know what it requires?

**Comment by kevinsumner** [comment]
I'll dig into it and maybe see about a PR.

**Comment by kevinsumner** [comment]
When trying to `go get` it, this is the issue:
```
$ go get -u github.com/DataFoxCo/gocsv
package github.com/DataFoxCo/gocsv: no Go files in /Users/ksumner/projects/go/src/github.com/DataFoxCo/gocsv
```

I think it's just a small amount of repository shuffling.
