### ISSUE TITLE
updates to tealeg/xlsx result in gocsv build errors

### ISSUE THREAD

**Issue by ezekiel** [aotimme/gocsv#22]
`go get github.com/DataFoxCo/gocsv` now results in:
```
src/github.com/DataFoxCo/gocsv/cmd/xlsx.go:105:27: sheet.Rows undefined (type *xlsx.Sheet has no field or method Rows)
```

**Comment by ezekiel** [comment]
@aotimme - How does the associated Pull Request look?

**Comment by aotimme** [comment]
Sorry for the very long delay. I just added a comment to #23

**Comment by flowrean** [comment]
I'm new to Go modules, but I think we could fix this by pinning the version of tealeg/xlsx to v1.0.5. Updating to a more recent version (and tackling breaking changes) could still be done in a separate issue.
With this, `go get` works again for me.

**Comment by ezekiel** [comment]
Yeah, I'm in favor of abandoning #23, merging #29 and tackling breaking changes separately.
