### ISSUE TITLE
How to use unique then save as a csv  name? 

### ISSUE THREAD

**Issue by sciefylab** [aotimme/gocsv#24]
How to use unique then save as a csv name?

**Comment by aotimme** [comment]
If I understand your question correctly, if you have an input file called `input.csv` and you want to use the `unique` subcommand and save the result to a new CSV, you can do the following (specify whichever flags you need):
```shell
gocsv unique [--columns COLUMNS] [--sorted] [--count] input.csv > output.csv
```

**Comment by sciefylab** [comment]
yes, thanks you @aotimme
