### ISSUE TITLE
Improving the release practice

### ISSUE THREAD

**Issue by flowrean** [aotimme/gocsv#31]
Hi,
Can I suggest an improvement to the release practice? Currently, the only release (described as ['Latest Release'](https://github.com/aotimme/gocsv/releases)) dates from 2016. The [documented way](https://github.com/aotimme/gocsv/blob/master/DEV.md) to make a release is to edit this release and update the binaries, which I think is not ideal. It is not clear how outdated the binaries actually are, which [already caused confusion](https://github.com/aotimme/gocsv/issues/18#issuecomment-677819651). Not to mention older releases are lost.
If we make new tagged releases from time to time, it should still be possible to refer to the latest release, e.g. in the macOS install script, as [this page](https://docs.github.com/en/github/administering-a-repository/linking-to-releases) details.
Although I don't have permission to actually make a release, I'd be happy to submit a pull request with some changes. Here's where I think updates might be required:

- scripts/update-latest-tag.sh
- scripts/install-latest-darwin-amd64.sh
- go.mod and cmd/go.mod (not sure)
- DEV.md
- README.md
- VERSION (starting with v1.0.0?)

**Comment by aotimme** [comment]
Yes I think that's a great idea. I've wanted to eventually institute semantic versioning on this tool, but I haven't gotten around to doing it... I think starting with v1.0.0 makes a lot of sense. Thanks!

**Comment by aotimme** [comment]
Closing due to the work done by @flowrean in #35. We will now only have semver versioned releases. Release v1.0.0 is now up: https://github.com/aotimme/gocsv/releases/tag/v1.0.0

**Comment by flowrean** [comment]
```shell
$ bash <(curl -sS https://raw.githubusercontent.com/aotimme/gocsv/master/scripts/install-latest-darwin-amd64.sh)
Checking permissions... ✔
Fetching binary... ✔
Extacting binary... ✔
Installing binary to /usr/local/bin/gocsv... ✔
Cleaning up... ✔

GoCSV has been successfully installed!
Open a new Terminal window and run:
  gocsv help
$ gocsv version
v1.0.0 (ab0261ba2538a9a2f712cf30f61fca69b940e894)
```
It's looking good 🥳
