### ISSUE TITLE
gocsv xlsx option does convert Exel date fields to numbers

### ISSUE THREAD

**Issue by calebeaires** [aotimme/gocsv#38]
Given this xlsv file wich d field is a date formated.

![image](https://user-images.githubusercontent.com/794195/108352240-572d1380-71c5-11eb-8f4a-d3bebeceb989.png)

The result is:
```csv
a,b,c,d
caleb,03/02/12,tyy,44197
```

Dates values became numbers. 

Ps.: Would be great if we could change the filename result!

**Comment by aotimme** [comment]
This appears to have been fixed by the switch to `github.com/xuri/excelize/v2` from `github.com/tealeg/xlsx` in 5fa735200fa31a49babc1d6787c0323c50294a42, which is in release [v1.0.2](https://github.com/aotimme/gocsv/releases/tag/v1.0.2).
