### ISSUE TITLE
Output column raw value

### ISSUE THREAD

**Issue by JamesColeman-LW** [aotimme/gocsv#44]
The program `jq` offers an option to output the raw value which is really useful in bash scripting, it would be nice of gocsv also had this to output a column without CSV formatting (quotes and new lines as `\n`) to allow querying and extracting data.

**Comment by zacharysyoung** [comment]
@JamesColeman-LW, will you please provide a sample CSV with the data you want to view as "raw", and how you expect it to look coming out of the command?

**Comment by aotimme** [comment]
Yeah I think we could do this. And it makes sense to follow the same API and semantics as `jq`'s `--raw-output` / `-r` flag. From https://stedolan.github.io/jq/manual/ (emphasis mine):
> With this option, **if the filter's result is a string** then it will be written directly to standard output rather than being formatted as a JSON string with quotes.

So what I think this means for `gocsv` is:
1. The `--raw-output` / `-r` would be an option _only_ for the `select` subcommand.
2. If the result of the `select` subcommand is just 1 column, it will output each cell as simple text (no quoting, etc.) if using the `--raw-output` / `-r` flag.
3. If the result of the `select` subcommand is more than 1 column, then the `--raw-output` / `-r` flag will do nothing.

Does that API / semantics make sense to you? If we agree, then I can implement it or someone else if they're interested!

**Comment by JamesColeman-LW** [comment]
That sounds reasonable to me.

**Comment by aotimme** [comment]
Done in cf64ecc96bcb9263f24f61a7c438ecc05eb697de, now in release [v1.0.2](https://github.com/aotimme/gocsv/releases/tag/v1.0.2).
