### ISSUE TITLE
Update Sprig to v3.2.1

### ISSUE THREAD

**Issue by zacharysyoung** [aotimme/gocsv#45]
GoCSV is currently using Sprig v3.1.0. The latest Sprig is v3.2.1, which notably has math functions for floats (3.1.0 only has integer math functions).

**Comment by aotimme** [comment]
Upgraded to Sprig v3.2.3 in 5fa735200fa31a49babc1d6787c0323c50294a42, now in release [v1.0.2](https://github.com/aotimme/gocsv/releases/tag/v1.0.2).
