### ISSUE TITLE
How to change to delim from "\x01" to others?

### ISSUE THREAD

**Issue by SysuJayce** [aotimme/gocsv#54]
Hello there, I have a csv file with "\x01" as delimiter and I want to use gocsv to change it to others like "," or "\t".

I have tried `head input | gocsv delim -i "\x01" -o "\t" > output`but nothing changed.

What should I do?

**Comment by aotimme** [comment]
I believe we can put up a fix for this. Would you be able to share a file that has this `\x01` delimiter so we can use it to verify a fix works?

**Comment by aotimme** [comment]
I believe this is fixed in the latest release: https://github.com/aotimme/gocsv/releases/tag/v1.0.4.

If not, please re-open!
