### ISSUE TITLE
replace into a new column

### ISSUE THREAD

**Issue by bsutton** [aotimme/gocsv#6]
I'm using the --regex and --repl args.

The problem is that I need to preserve the original column.

what I really want to do is output the results of the replace into a new column.

**Comment by aotimme** [comment]
To do this I will often add a `select` beforehand to duplicate the column and then run a `replace` on the duplicated column.

e.g. if my CSV just has two columns and I want to replace something in the second column and store that in a third column with a new name ("Name" here), I might do
```shell
cat myfile.csv | gocsv select -c 1,2,2 | gocsv replace -c 3 --regex "Hello, (.*)!" --repl "\$1" | gocsv rename -c 3 --names Name
```

I'm not opposed to adding a feature to copy the replaced column into a new column, but I'm not sure what the optimal set of flags should look like for that option.

Do you have any suggestions on how it should look? Would you expect the new column to have the same header name or would you want to be able to specify the header for the new column?

**Comment by bsutton** [comment]
Yes I've been playing and found the select syntax to duplicate columns.
I hadn't noticed the rename and combining the select and rename clearly works but maybe something like this would be more obvious

gocsv copy -c "ContactName" -name "NewContactName"

The copied field would be appended to the csv row.

**Comment by bsutton** [comment]
btw: nice tool, saved me hours, so thanks!

**Comment by aotimme** [comment]
I think the `add` subcommand along with the addition of sprig (#28) should handle this case really well now. I'm going to close this.
